#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright (c) 2014-2020 Iruatã Martins dos Santos Souza

if [ -z `which dialexec` ]; then
	(lua testclient.lua < /tmp/srv-cli) > /tmp/cli-srv
else
	dialexec localhost:9999 lua testclient.lua
fi

